### ISSUE TITLE
Does not work on TFS 2015 XAML Build

### ISSUE THREAD

**Issue by sheitmann** [KirillOsenkov/LargeAddressAware#1]
Hi

When I compile my solution in Visual Studio everything is working as expected.
When I run it on my TFS build server editbin seems not to be run.
I have a TFS 2015 with XAML builds. I use the old nuget restore method.

From a diagnostic log I can see that the property is set
 LargeAddressAware = true

that the package is restored correctly 
 Installing 'LargeAddressAware 1.0.0'. (Aufgaben-ID: 825)
 Successfully installed 'LargeAddressAware 1.0.0'. (Aufgaben-ID: 825)

And that the error task checking if the targets file exists was skiped
Die Error-Aufgabe wurde übersprungen, da die Bedingung "false" war . (!Exists('..\..\..\packages\LargeAddressAware.1.0.0\build\LargeAddressAware.targets')) wurde als (!Exists('..\..\..\packages\LargeAddressAware.1.0.0\build\LargeAddressAware.targets')) ausgewertet.

But it seems it is not executed. I also do not see the property EditBin anywhere in the log file.

Do you have any idea what's going wrong?

Br
Sven

P.S.
I tried it with the vNext build I have, this works very well.

**Comment by KirillOsenkov** [comment]
Hi, sorry, I have no idea what might be going on there. Did you solve it yet by any chance?
