### ISSUE TITLE
Not working in .Net Core

### ISSUE THREAD

**Issue by david289868** [KirillOsenkov/LargeAddressAware#11]
We have used this on .net Framework projects but now that we have migrated two projects to .net core, it seems that the large address aware flag isn't being set. Should it work with .net core?

We have added the nuget package and added a property group containing 
`  <LargeAddressAware>true</LargeAddressAware>`

**Comment by david289868** [comment]
It appears that it is trying to set the large address aware flag onto a DLL whereas the project output is an EXE.

**Comment by KirillOsenkov** [comment]
Yes, this can't work on .NET Core because either you're using dotnet.exe (32-bit or 64-bit) that we don't control, or a custom entrypoint .exe which we also don't control. You shouldn't need this either, just use 64-bit dotnet.

**Comment by david289868** [comment]
Thank you for your reply. Unfortunately we do need to set the LARGEADDRESSAWARE flag as linking in to an x86 component. We'll just have to do it the hard ward.

**Comment by KirillOsenkov** [comment]
You can still use parts of this NuGet package I think. May need some tweaking for your scenario. Good luck.

**Comment by ig-jb** [comment]
Thanks for your work on this project.

> Yes, this can't work on .NET Core because either you're using dotnet.exe (32-bit or 64-bit) that we don't control, or a custom entrypoint .exe which we also don't control. You shouldn't need this either, just use 64-bit dotnet.

A common use case for this is if you're using legacy COM in which case you need your executable to be architecture matched to the COM component e.g. MS Office applications. Legacy COM is currently the only option if you are using AxHost as COM source generator support isn't ready there yet. 

> You can still use parts of this NuGet package I think. May need some tweaking for your scenario. Good luck.

I have confirmed this library works in .NET 8 with some tweaks.

```
<LargeAddressAware>true</LargeAddressAware>
<LargeAddressAwareAfterTargets>PostBuildEvent</LargeAddressAwareAfterTargets>
<LargeAddressAwareTargetAssembly>$(OutDir)\YourProject.exe</LargeAddressAwareTargetAssembly>
```
