### ISSUE TITLE
MSBuild task assembly

### ISSUE THREAD

**Issue by jeffkl** [KirillOsenkov/LargeAddressAware#2]
Can I make this into a proper MSBuild task DLL?  Does it need to be an executable?

**Comment by KirillOsenkov** [comment]
Nope, go ahead! Was just for convenience. PRs welcome :)

**Comment by jeffkl** [comment]
Great, do you want me to leave it as an executable or can I just make it a class library?

**Comment by KirillOsenkov** [comment]
Whatever works best for your goals. It's convenient to have an .exe in one's toolbelt for one-off manual applications, but then again, you could just do `editbin /LARGEADDRESSAWARE msbuild.exe`.

I'd say go ahead and change it. It's strange to have tasks in an .exe.
