### ISSUE TITLE
Issue with winforms project

### ISSUE THREAD

**Issue by MetaSam** [KirillOsenkov/LargeAddressAware#4]
Hi,

It does not work out of the box with my VB Winforms project (under VS2017). Here's the MSBuild log message. The output type is 'WinExe' instead of the expected 'Exe'.

Cible "SetLargeAddressAware" ignorée en raison d'une fausse condition ; ( '$(LargeAddressAware)' == 'true' And Exists('$(LargeAddressAwareAssemblyFile)') And '$(OutputType)' == 'Exe' And '$(PlatformTarget)' == 'x86' ) a été évaluée comme ( 'true' == 'true' And Exists('C:\Users\Samuel\Documents\Code\syncrun.net\Clients\RTA_Shawinigan\packages\LargeAddressAware.1.0.2\build\net46\SetLargeAddressAware.dll') And 'WinExe' == 'Exe' And 'x86' == 'x86' ).

When I change 'Exe' to 'WinExe' in the targets file it does work.

This documentation could be useful: https://msdn.microsoft.com/en-us/library/bb629394.aspx (See OutputType section for all possible OutputType values)

**Comment by KirillOsenkov** [comment]
This should be fixed with https://github.com/KirillOsenkov/LargeAddressAware/commit/909a19781b5c70d1ab9f9e0cb467a28e60579504

**Comment by KirillOsenkov** [comment]
Uploaded https://www.nuget.org/packages/LargeAddressAware/1.0.3

**Comment by MetaSam** [comment]
That was a quick fix! Thanks!
